### ISSUE TITLE
Performance on D4RL AntMaze tasks?

### ISSUE THREAD

**Issue by yuxudong20** [snu-mllab/EDAC#1]
Hello, I have a question about the performance of SAC-N or EDAC on AntMaze tasks. Have you ever tested it?

In my experiments based on this official implementation, I found that average returns in evaluation are always 0, which is worse than behavior cloning. Then I try to run with a modified reward (r=4*(r-0.5)) and max Q backup. However, they didn't help. 

I'll appreciate it a lot if you give me some related advices. Thanks a lot.

**Comment by yuxudong20** [comment]
@drillermoon @dssrgu

**Comment by dssrgu** [comment]
Hi,

As we have not done any experiments on Antmaze, it is hard to tell what would specifically be the problem.
However, I recommend checking if quantitative statistics such as Q-values have reasonable values while tuning the hyperparameters.

Thank you.

**Comment by gaisibo** [comment]
Hello,
    Do you have got reasonable results in AntMaze tasks? I have the same question.
    Thanks a lot.
@yuxudong20
